/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectobd;

import com.mycompany.proyectobd.leo.usuario;
import com.mycompany.proyectobd.leo.usuario_frame;
import com.mycompany.proyectobd.leo.alumno_frame;
import com.mycompany.proyectobd.jorge.JProducto;
import com.mycompany.proyectobd.socrucito.Producto;
import com.mycompany.proyectobd.leo.agregar_alumno;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;

/**
 *
 * @author jorge
 */
public class JAdmin extends javax.swing.JFrame {

    /**
     * Creates new form JAdmin
     */
    public JAdmin() {
        initComponents();

        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_navegador = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton_ingresarUsuario = new javax.swing.JButton();
        jButton_BecarioNuevo2 = new javax.swing.JButton();
        jButton_CrearEvento = new javax.swing.JButton();
        jButtonSeguimientoBeca = new javax.swing.JButton();
        jButtonGenrarReporte = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_navegador.setBackground(new java.awt.Color(102, 153, 255));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setForeground(new java.awt.Color(0, 51, 51));

        jButton_ingresarUsuario.setBackground(new java.awt.Color(0, 0, 204));
        jButton_ingresarUsuario.setText("Ingresar Usuario");
        jButton_ingresarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ingresarUsuarioActionPerformed(evt);
            }
        });

        jButton_BecarioNuevo2.setText("Becario nuevo");
        jButton_BecarioNuevo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BecarioNuevo2ActionPerformed(evt);
            }
        });

        jButton_CrearEvento.setText("Nuevo evento");
        jButton_CrearEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CrearEventoActionPerformed(evt);
            }
        });

        jButtonSeguimientoBeca.setText("Seguimiento beca");
        jButtonSeguimientoBeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeguimientoBecaActionPerformed(evt);
            }
        });

        jButtonGenrarReporte.setText("Generar Reporte ");
        jButtonGenrarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenrarReporteActionPerformed(evt);
            }
        });

        jButton2.setText("Inventario");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setText("Administrador ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton_ingresarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 132,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32,
                                        Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jButton_BecarioNuevo2,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 110,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(42, 42, 42))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jButtonSeguimientoBeca,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 132,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(27, 27, 27)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton_CrearEvento)
                                        .addComponent(jButtonGenrarReporte))
                                .addGap(47, 47, 47))

        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton_ingresarUsuario)
                                        .addComponent(jButton_BecarioNuevo2))
                                .addGap(53, 53, 53)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonSeguimientoBeca)
                                        .addComponent(jButtonGenrarReporte)
                                        .addComponent(jButton2))
                                .addContainerGap(112, Short.MAX_VALUE)));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_navegadorLayout = new javax.swing.GroupLayout(jPanel_navegador);
        jPanel_navegador.setLayout(jPanel_navegadorLayout);
        jPanel_navegadorLayout.setHorizontalGroup(
                jPanel_navegadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_navegadorLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton1)
                                .addGap(80, 80, 80)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(171, Short.MAX_VALUE)));
        jPanel_navegadorLayout.setVerticalGroup(
                jPanel_navegadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_navegadorLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jButton1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel_navegadorLayout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));

        getContentPane().add(jPanel_navegador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 410));
        getContentPane().add(jLabel_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected void jButton_CrearEventoActionPerformed(ActionEvent evt) {
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        JProducto producto = new JProducto();
        producto.setVisible(true);

    }// GEN-LAST:event_jButton2ActionPerformed

    private void jButtonGenrarReporteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonGenrarReporteActionPerformed
        // TODO add your handling code here:
        reportes NuevoReporte = new reportes();
        NuevoReporte.setVisible(true);
    }// GEN-LAST:event_jButtonGenrarReporteActionPerformed

    private void jButtonSeguimientoBecaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonSeguimientoBecaActionPerformed
        // TODO add your handling code here:
        alumno_frame SeguimientoBeca = new alumno_frame();
        SeguimientoBeca.setVisible(true);
    }// GEN-LAST:event_jButtonSeguimientoBecaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed

        // TODO add your handling code here:

        CrearEvento interfaceNuevoEvento = new CrearEvento();
        interfaceNuevoEvento.setVisible(true);
    }// GEN-LAST:event_jButton_CrearEventoActionPerformed

    private void jButton_BecarioNuevo2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_BecarioNuevo2ActionPerformed
        // TODO add your handling code here:
        agregar_alumno NuevoAlumno = new agregar_alumno();
        NuevoAlumno.setVisible(true);

        // NuevoAlumno.setVisible(true);
    }// GEN-LAST:event_jButton_BecarioNuevo2ActionPerformed

    private void jButton_ingresarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_ingresarUsuarioActionPerformed
        // TODO add your handling code here:
        // llamar al jframe de ingresar usuario
        usuario_frame interface_Usuario = new usuario_frame();
        interface_Usuario.setVisible(true);

    }// GEN-LAST:event_jButton_ingresarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonGenrarReporte;
    private javax.swing.JButton jButtonSeguimientoBeca;
    private javax.swing.JButton jButton_BecarioNuevo2;
    private javax.swing.JButton jButton_CrearEvento;
    private javax.swing.JButton jButton_ingresarUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_fondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_navegador;
    // End of variables declaration//GEN-END:variables
}
