/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.proyectobd;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.pdf.PdfPTable;
import java.io.*; 
import com.mycompany.proyectobd.Conexion;
import javax.swing.*;
import java.sql.*;
//import com.itextpdf.text.Document;
//import com.itextpdf.text.DocumentException;
//import com.itextpdf.text.pdf.PdfWriter;
/**
 *
 * @author hp
 */
public class reportes extends javax.swing.JFrame {

    /**
     * Creates new form reportes
     */
    public reportes() {
        initComponents();
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_tipoReporte = new javax.swing.JLabel();
        jLabel_tiempo = new javax.swing.JLabel();
        jComboBox_tipoReporte = new javax.swing.JComboBox<>();
        jLabel_generarReporte = new javax.swing.JLabel();
        jComboBox_Tiempo = new javax.swing.JComboBox<>();
        jButton_generarReporte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 153));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel_tipoReporte.setText("tipo reporte");

        jLabel_tiempo.setText("tiempo");

        jComboBox_tipoReporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "reporte ventas", "reporte eventos", "sin reporte" }));
        jComboBox_tipoReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_tipoReporteActionPerformed(evt);
            }
        });

        jLabel_generarReporte.setText("Generar reporte");

        jComboBox_Tiempo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "mes", "año" }));
        jComboBox_Tiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_TiempoActionPerformed(evt);
            }
        });

        jButton_generarReporte.setText("Generar Reporte");
        jButton_generarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_generarReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_tipoReporte)
                    .addComponent(jLabel_tiempo)
                    .addComponent(jLabel_generarReporte))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_generarReporte)
                    .addComponent(jComboBox_Tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_tipoReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_tipoReporte)
                    .addComponent(jComboBox_tipoReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_tiempo)
                    .addComponent(jComboBox_Tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_generarReporte)
                    .addComponent(jButton_generarReporte))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_tipoReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_tipoReporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_tipoReporteActionPerformed

    private void jComboBox_TiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_TiempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_TiempoActionPerformed

    private void jButton_generarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_generarReporteActionPerformed
        // TODO add your handling code here:
        String tipo_Reporte = jComboBox_tipoReporte.getSelectedItem().toString();
        String tiempo = jComboBox_Tiempo.getSelectedItem().toString();
        String Consulta = "";
        Document documento = new Document();
         String ruta = System.getProperty("user.home");
        
       System.out.println("Numero:"+tipo_Reporte.compareTo("reporte ventas"));
       
        if(tipo_Reporte.compareTo("reporte eventos")==0) {
              // System.out.println("entro al if");
            if(!(tiempo.isEmpty())) {
                try {
                   
                    System.out.print(ruta + "/Desktop/ReporteEventos1.pdf");
                    PdfWriter.getInstance(documento, new FileOutputStream(ruta + "/Desktop/ReporteEventos.pdf"));
                    documento.open();
                    PdfPTable tabla = new PdfPTable(6);
                
                    tabla.addCell("evento");
                    tabla.addCell("lugar");
                    tabla.addCell("menu");
                    tabla.addCell("numero platillos");
                    tabla.addCell("Precio menu");
                    tabla.addCell("Total");

                    Conexion objetoConexion = new Conexion();
                    System.out.println("AQUI");
                    if(tiempo.compareTo("mes") == 0) {
                        System.out.println("INGRESO A MES");
                        Consulta = "SELECT e.nombre_evento , e.lugar_evento, m.nombre_menu , m.numero_platillos,m.precio_menu , (m.precio_menu * m.numero_platillos)  FROM eventos e JOIN menu_evento m ON e.id_evento = m.id_evento WHERE MONTH(e.fecha_evento) = MONTH(CURRENT_DATE) AND YEAR(e.fecha_evento) = YEAR(CURRENT_DATE)";
                    }else if(tiempo.compareTo("año") == 0) {
                        Consulta = "SELECT e.nombre_evento , e.lugar_evento, m.nombre_menu , m.numero_platillos,m.precio_menu , (m.precio_menu * m.numero_platillos) FROM eventos e JOIN menu_evento m ON e.id_evento = m.id_evento WHERE  YEAR(e.fecha_evento) = YEAR(CURRENT_DATE)";
                    }
                    Statement st1;
                    try {

                        st1 = objetoConexion.establecerConexion().createStatement();
                        ResultSet rs = st1.executeQuery(Consulta);
                        while (rs.next()) {
                          
                            tabla.addCell(rs.getString(1));
                            tabla.addCell(rs.getString(2));
                            tabla.addCell(rs.getString(3));
                            tabla.addCell(rs.getString(4));
                            tabla.addCell(rs.getString(5));
                            tabla.addCell(rs.getString(6));
                            documento.add(tabla);
                        }
                        System.out.print("se ejecuto");

                    } catch (DocumentException | SQLException e) {
                        JOptionPane.showMessageDialog(null, "NO SE PUDO REALIZAR LA CONSULTA de mes");
                    }

                    documento.close();
                    JOptionPane.showMessageDialog(null, "PDF creado correctamente");

                } catch (DocumentException | FileNotFoundException e) {
                    JOptionPane.showMessageDialog(null, "NO SE PUDO GENERAR EL REPORTE" + e);
                }

            } 
        }else if(tipo_Reporte.compareTo("reporte ventas") ==0 ) {
              System.out.println("entro al if");
                if(!(tiempo.isEmpty())) {
                    try {
        
                        PdfWriter.getInstance(documento, new FileOutputStream(ruta + "/Desktop/ReporteVentas.pdf"));
                        documento.open();
                        PdfPTable tabla2 = new PdfPTable(6);
                        tabla2.addCell("Desayuno A");
                        tabla2.addCell("Desayuno B");
                        tabla2.addCell("Comida A");
                        tabla2.addCell("Comida B");
                        tabla2.addCell("precio total");
                        tabla2.addCell("Total vendidos");
                        Conexion objetoConexion1 = new Conexion();
                         System.out.println("AQUI22");
                         if(tiempo.compareTo("mes") == 0) {
                        System.out.println("INGRESO A MES");
                        Consulta = "SELECT * FROM alimentos ";
                    }else if(tiempo.compareTo("año") == 0) {
                         System.out.println("INGRESO A anio");
                        Consulta = "SELECT * FROM alimentos";
                    }   
                       
                        Statement st1;
                        try {

                            st1 = objetoConexion1.establecerConexion().createStatement();
                            ResultSet rs2 = st1.executeQuery(Consulta);
                            while (rs2.next()) {
                            tabla2.addCell(rs2.getString(1));
                            tabla2.addCell(rs2.getString(2));
                            tabla2.addCell(rs2.getString(3));
                            tabla2.addCell(rs2.getString(4));
                            tabla2.addCell(rs2.getString(5));
                            tabla2.addCell(rs2.getString(6));
                            documento.add(tabla2);
                            }

                        } catch (DocumentException | SQLException e) {
                            JOptionPane.showMessageDialog(null, "NO SE PUDO REALIZAR LA CONSULTA DEL REPORTE");
                        }

                        documento.close();
                        JOptionPane.showMessageDialog(null, "PDF creado correctamente");

                    } catch (DocumentException | FileNotFoundException e) {
                        JOptionPane.showMessageDialog(null, "NO SE PUDO GENERAR EL REPORTE"+e);
                    }

                }

            } else if(tipo_Reporte.compareTo("sin reporte")== 0 ) {
                 JOptionPane.showMessageDialog(null, "Elige una opcion de evento");    
                 return;
            }
    }//GEN-LAST:event_jButton_generarReporteActionPerformed
    
    
    
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
         String botones[]={"Cerrar","Cancelar"};
        int eleccion = JOptionPane.showOptionDialog(this,"Desea cerrar la ventana","Titulo",0,0,null,botones,this);
        if(eleccion == JOptionPane.YES_OPTION){
            this.dispose();
        }else if(eleccion==JOptionPane.NO_OPTION){
            System.out.println("Se cancelo el cierre ");
           //JOptionPane.showConfirmDialog("pasa", evt);
        }
        
    }//GEN-LAST:event_formWindowClosing
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_generarReporte;
    private javax.swing.JComboBox<String> jComboBox_Tiempo;
    private javax.swing.JComboBox<String> jComboBox_tipoReporte;
    private javax.swing.JLabel jLabel_generarReporte;
    private javax.swing.JLabel jLabel_tiempo;
    private javax.swing.JLabel jLabel_tipoReporte;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
