/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.proyectobd;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.pdf.PdfPTable;
import java.io.*; 
import com.mycompany.proyectobd.Conexion;
import javax.swing.*;
import java.sql.*;
//import com.itextpdf.text.Document;
//import com.itextpdf.text.DocumentException;
//import com.itextpdf.text.pdf.PdfWriter;
/**
 *
 * @author hp
 */
public class reportes extends javax.swing.JFrame {

    /**
     * Creates new form reportes
     */
    public reportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_tipoReporte = new javax.swing.JLabel();
        jLabel_tiempo = new javax.swing.JLabel();
        jComboBox_tipoReporte = new javax.swing.JComboBox<>();
        jLabel_generarReporte = new javax.swing.JLabel();
        jComboBox_Tiempo = new javax.swing.JComboBox<>();
        jButton_generarReporte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_tipoReporte.setText("tipo reporte");

        jLabel_tiempo.setText("tiempo");

        jComboBox_tipoReporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "reporte ventas", "reporte eventos" }));
        jComboBox_tipoReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_tipoReporteActionPerformed(evt);
            }
        });

        jLabel_generarReporte.setText("Generar reporte");

        jComboBox_Tiempo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "mes", "semestre", "año" }));
        jComboBox_Tiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_TiempoActionPerformed(evt);
            }
        });

        jButton_generarReporte.setText("Generar Reporte");
        jButton_generarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_generarReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_tipoReporte)
                    .addComponent(jLabel_tiempo)
                    .addComponent(jLabel_generarReporte))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_generarReporte)
                    .addComponent(jComboBox_Tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_tipoReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(331, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_tipoReporte)
                    .addComponent(jComboBox_tipoReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_tiempo)
                    .addComponent(jComboBox_Tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_generarReporte)
                    .addComponent(jButton_generarReporte))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_tipoReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_tipoReporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_tipoReporteActionPerformed

    private void jComboBox_TiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_TiempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_TiempoActionPerformed

    private void jButton_generarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_generarReporteActionPerformed
        // TODO add your handling code here:
        String tipo_Reporte = jComboBox_tipoReporte.getSelectedItem().toString();
        String tiempo = jComboBox_Tiempo.getSelectedItem().toString();
        Document documento = new Document();
        if (!(tipo_Reporte.isEmpty() && tiempo.isEmpty())) {
            try {
                String ruta = System.getProperty("user.name");
                PdfWriter.getInstance(documento, new FileOutputStream(ruta + "/Desktop/Reporte_Ventas.pdf"));
                documento.open();
                PdfPTable tabla = new PdfPTable(3);
                tabla.addCell("Repore");
                tabla.addCell("Tiempo");
                tabla.addCell("cantidad vendida");
                Conexion objetoConexion = new Conexion();

                String Consulta = "Select * from detalleVenta";
                Statement st;
                try {

                    st = objetoConexion.establecerConexion().createStatement();
                    ResultSet rs = st.executeQuery(Consulta);
                    while (rs.next()) {
                        tabla.addCell(rs.getString(1));
                        tabla.addCell(rs.getString(2));
                        tabla.addCell(rs.getString(3));
                        documento.add(tabla);
                    }

                } catch (DocumentException | SQLException e) {
                    JOptionPane.showMessageDialog(null, "NO SE PUDO REALIZAR LA CONSULTA");
                }

                documento.close();
                JOptionPane.showMessageDialog(null, "PDF creado correctamente");

            } catch (DocumentException | FileNotFoundException e) {
                JOptionPane.showMessageDialog(null, "NO SE PUDO GENERAR EL REPORTE");
            }

        }

             
    }//GEN-LAST:event_jButton_generarReporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_generarReporte;
    private javax.swing.JComboBox<String> jComboBox_Tiempo;
    private javax.swing.JComboBox<String> jComboBox_tipoReporte;
    private javax.swing.JLabel jLabel_generarReporte;
    private javax.swing.JLabel jLabel_tiempo;
    private javax.swing.JLabel jLabel_tipoReporte;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
